accepted = [
    "Apache-2.0 WITH LLVM-exception", "Apache-2.0", "MIT", "Unicode-3.0",
    "MPL-2.0", "CDLA-Permissive-2.0", "BSD-3-Clause", "BSD-2-Clause",
    "Zlib", "ISC", "Unlicense", "0BSD", "CC0-1.0", "MIT-0",
]
targets = ["aarch64-apple-darwin"]
ignore-build-dependencies = false
private = { ignore = true }
